run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    # basic - most important
    - govet
    - staticcheck
    - gosimple
    - unused
    # style - formatting only
    - gofmt
    - goimports
    # minor issues
    - misspell
  disable:
    # Too noisy or require extensive refactoring
    - errcheck      # Many false positives with defer
    - ineffassign   
    - stylecheck
    - dupl
    - wsl
    - goconst
    - funlen
    - gocyclo
    - lll
    - gosec         # Flags legitimate uses of md5/sha1 for ETags

linters-settings:
  gocyclo:
    min-complexity: 25  # More lenient
  misspell:
    locale: US
    ignore-words:
      - auther  # Not a typo, it's our interface name for "authentication provider"

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    # Exclude www directory (frontend code)
    - path: www/
      linters:
        - all
    # Exclude test files from some checks
    - path: _test\.go
      linters:
        - all
