project_name: nulyun

builds:
  - id: nulyun
    main: .
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

changelog:
  use: git


release:
  github:
    owner: nulnl
    name: nulyun

# Notes:
# - Publishes to GitHub Container Registry (ghcr.io) using Dockerfile (Alpine).
# - Produces amd64 and arm64 images and a manifest pointing to both.
# - Replace 'YOUR_GITHUB_ORG' and 'YOUR_REPO' with your GitHub org/user and repo name.
# - Ensure the release workflow has `packages: write` permission and `GITHUB_TOKEN` is present.
