project_name: nulyun

builds:
  - id: nulyun
    main: .
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

changelog:
  use: git

dockers:
  # Use the Alpine Dockerfile and publish only amd64 and arm64 images to GHCR
  - dockerfile: Dockerfile
    use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/nulyun:{{ .Tag }}-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
  - dockerfile: Dockerfile
    use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/nulyun:{{ .Tag }}-arm64"
    build_flag_templates:
      - "--platform=linux/arm64"

docker_manifests:
  - name_template: "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/nulyun:{{ .Tag }}"
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/nulyun:{{ .Tag }}-amd64"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/nulyun:{{ .Tag }}-arm64"

release:
  github:
    owner: nulnl
    name: nulyun

# Notes:
# - Publishes to GitHub Container Registry (ghcr.io) using Dockerfile (Alpine).
# - Produces amd64 and arm64 images and a manifest pointing to both.
# - Replace 'YOUR_GITHUB_ORG' and 'YOUR_REPO' with your GitHub org/user and repo name.
# - Ensure the release workflow has `packages: write` permission and `GITHUB_TOKEN` is present.
