version: 2

project_name: nulyun

builds:
  - id: nulyun
    main: ./cmd/nulyun
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - LICENSE
      - README.md

changelog:
  use: git

release:
  draft: true
  github:
    owner: nulnl
    name: nulyun

# Notes:
# - Publishes to GitHub Container Registry (ghcr.io) using Dockerfile (Alpine).
# - Produces amd64 and arm64 images and a manifest pointing to both.
# - Replace 'YOUR_GITHUB_ORG' and 'YOUR_REPO' with your GitHub org/user and repo name.
# - Ensure the release workflow has `packages: write` permission and `GITHUB_TOKEN` is present.
